---
title: "Data Science for the Natural Environment (FA21)"
subtitle: "BI449 Data Science for the Natural Environment"
author: "Shannon J. O'Leary"
date: "`r Sys.Date()`"
knit: "bookdown::preview_chapter"
output:
  msmbstyle::msmb_html_book:
    highlight: tango
    toc: TRUE
    toc_depth: 1
    split_by: chapter
    margin_references: FALSE
    css: msmb.css
bibliography: labmanual.bib
link-citations: yes
---

```{r include=FALSE}

library(msmbstyle)

# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('msmbstyle'))
options(htmltools.dir.version = FALSE)

```

# Identifying essential fish habitat: Shark Nurseries on the Texas coast

**Learning Objectives**

After completing this activity you should be able to

* define essential fish habitats and shark nurseries.
* understand how differences in methodology can affect a data set.

For each of our modules we will have a project-folder with an `Rproject`, `*.Rmd`-files, and sub-directories for data, scripts, and results as described in our `Rproject` Tutorial. You should create a directory on your Desktop or Documents folder on your laptop (name it something like `BI449`) as a home directory for all of our project folders this semester. 

Download the [SharkNurseries]() project folder. Once you have downloaded it, unzip the project directory into your `BI449` directory. You can open the `Rproj` for this module either by double clicking on it which will launch `Rstudio` or by opening `Rstudio` and then using `File > Open Project` or by clicking on the `Rproject` icon in the top right of your program window and selecting `Open Project`. 

Once you have opened a project you should see the project name in the top right corner^[Pro tip: If you run into issues where an Rmarkdown won't render or file paths aren't working (especially if things were working previously) one of your first steps should be to double check that the correct `Rproj` is loaded.].

You should have a `SharkNurseries.Rmd` in your project directory. Use that file to work through this tutorial - you will hand in your rendered ("knitted") rmarkdown file as your homework assignment. So, first thing in the `YAML` header, change the author to your name. You will use this `Rmarkdown` file to record your answers. Remember to use comments to describe your code; at minimum you should have one comment per code set^[You should do this even if you are adding code yourself or if you are using code from our manual, even if it isn't commented in the manual ... you may of course add as many comments as you need to be able to recall what you did].


## Essential fish habitat: Shark Nurseries

The [Magnuson-Stevens Act](https://www.federalregister.gov/documents/2002/01/17/02-885/magnuson-stevens-act-provisions-essential-fish-habitat-efh) (1996) defined essential fish habitat as "those waters and substrate necessary to fish for spawning, breeding, feeding or growth to maturity", i.e. they are habitats necessary for an organism to complete their life cycle. Identifying essential fish habitats is critical for management and conservation plans because it enables policy makers to prioritize certain ecosystems.

While some elasmobranchs (sharks, rays, skates) inhabit estuaries year round, many use the estuaries for specific purposes such as feeding, mating, gestation, parturition or as nurseries and only inhabit them during specific life history stages. Estuaries are heavily impacted by humans - overfishing, pollution, habitat destruction and altered flow regimes all affect the biological communities they support.

Broadly, shark nurseries are areas where young are born and/or reside in during maturation. Typically, these would areas that provide additional protection (e.g. mangroves for hiding) and plenty of food. Heupel et al. [@Heupel2007, Heupel2019] developed three criteria to defining shark nurseries as 

1. an area where sharks are commonly encountered within compared to outside of.
2. an area in which Young-of-the-year (YOY)/juveniles remain or return to for extended periods of time.
3. an area that is repeatedly used across years.

`r msmbstyle::question(label = "ques:sh-1", text = "Consider how you could design a study to identify estuaries that are shark nurseries.")`


## Identifying shark nurseries on the Texas Coast

Texas Parks and Wildlife (TPWD) defines eight major estuaries along the Texas coastline and performs regular shore-based gill net surveys for 10 week periods in April - June and September to November. Analysis of this survey has identify eight elasmobranch species [@Plumlee2018].

* Bull shark
* Bonnethead
* Cownose ray
* Blacktip shark
* Atlantic stingray
* Atlantic sharpnose shark
* Spinner shark
* Scalloped hammerhead 
* Finetooth shark
* Lemon shark

Gill nets generally exclude individuals > 2m.

More recently, a multi-year open water long-lining study targeting elasmobranchs was performed in three estuarine locations near Corpus Christi, TX that are considered putative shark nurseries. Here, the sampling period lasted from May to November [@Swift2020].

`r msmbstyle::question(label = "ques:sh-2", text = "Discuss whether or not you would expect to get similar results from both studies and what factors could result in differences.")`

`r msmbstyle::solution_begin()`

Here are some things to consider: 

* gear-bias (hook size, net-size)
* seasonality (peak use for many coastal elasmobranchs is May - Oct)
* spatial (land-based vs open ocean)

`r msmbstyle::solution_end()`

This study wanted to answer four questions to further understand whether these locations should be considered shark nurseries and therefore as essential fish habitat for specific elasmobranch species.

1. How does the composition of elasmobranch communities compare across sites?
2. How does the catch-per-unit-effort (CPUE) per species and life history compare across sites?
3. What do the sex ratios look like?
4. What environmental predictors can we use to predict presence of elasmobranchs?


## Explore the data set

There should be a an excel file in the `data` folder of your project directory named `catch.xls`. Go ahead and open the file in excel.

`r msmbstyle::question(label = "ques:sh-3", text = "Take a look at the excel file and describe how you would figure out what the dimensions are (how many rows? columns?) and see if you identifying what information is contained in each column.")`

`r msmbstyle::solution(text = "The data set contains information on the sampling site, Species name, Sex, life history stage, Pre-caudal length (PCL), fork length (FL), stretch total length (STL), Hook Size, and the set number and sampling date.")`

While some column headers were probably more easy to identify than others a good data set comes with meta data - this is data about the data. At minimum it should contain detailed information on what is contained in each column, frequently it may also contain information on how certain data was calculated/generated.

Now that we're looking at the data set we might as well take a stab at the first question.

> How does the composition of elasmobranch communities compare across sites?

`r msmbstyle::question_begin(label = "ques:sh-4")`

Use your excel skills to create sets of summary tables

* Total catch:
    + total number of individuals per elasmobranch species caught at each site (across all years).
    + relative abundance of each elasmobranch species caught per site.
* Relative abundance:
    + total number of individuals per elasmobranch species per site and year.
    + relative abundance per of each elasmobranch species per site and year.
* Summary stats size:
    + mean size of sharks (exclude rays) by site.
    + minimum size per shark species by site.
    + maximum size per shark species by site.

`r msmbstyle::question_end()`

`r msmbstyle::question(label = "ques:sh-5", text = "Imagine that just as you finished creating these summary stats tables your lab mate comes in tells you that they just discovered three data sheets in a drawer that wasn't entered in with the other data. How easy would it be to update your results tables? Consider disadvantages of using Excel to analyze your data in this way.")`


## Export as text file

Our next step is to learn how to use `R` to wrangle data, this can include both cleaning up your data to put it into a standard format or analysis as well as using a raw data set to generate a data sets based of off them for further analysis or summarize results.

Two of the most common file formats you are going to encounter when you access or download data sets are `*.csv` (comma-delimited files) and tab-delimited files (`*txt`); both of these are straightforward to read into `R`. You can convert your excel file into these formats by using `File > Save As` and then selecting the appropriate file formats.

`r msmbstyle::question(label = "ques:sh-6", text = "Go ahead and save a csv and tab-delimited formatted version of our data set in your data folder. Then open those files in a text editor and describe the difference between the two formats and briefly discuss the advantages of storing large data sets in these formats over a typical excel file.")`