---
title: "Data Science for the Natural Environment (FA21)"
subtitle: "BI449 Data Science for the Natural Environment"
author: "Shannon J. O'Leary"
date: "`r Sys.Date()`"
knit: "bookdown::preview_chapter"
output:
  msmbstyle::msmb_html_book:
    highlight: tango
    toc: TRUE
    toc_depth: 1
    split_by: chapter
    margin_references: FALSE
    css: msmb.css
bibliography: labmanual.bib
link-citations: yes
---

```{r include=FALSE}

library(msmbstyle)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('msmbstyle'))
options(htmltools.dir.version = FALSE)

```

# Title

**Date**:

**Learning Objectives**

After completing this tutorial you should be able to

* * describe how deliberate misinformation campaigns neglecting the existence, anthropogenic cause and/or impacts of climate change have resulted in high levels of climate change skepticism in the US



## A picture is worth a thousand words*

* ...when appropriately placed in context.

`r tufte::margin_note("Harold Evans")`

> *The camera cannot lie but it can be an accessory to untruth.*

`r msmbstyle::question_begin(label = ques:misinf-)`

Use the above quote to briefly discuss argue the use of photographs in a manipulative way is such a powerful tool, especially for climate skeptics and deniers.

`r msmbstyle::question_end()`



## Header


Some examples of strategies employed by climate deniers and skeptics using visualizations are drawn from Schneider et al. "Twist and Shout: Images and Graphs in Skeptical Media".
